/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diary_crud;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author decastrodaniel
 */
public class Main extends javax.swing.JFrame {

    DatabaseCon dbcon = new DatabaseCon();
    int b;

    private void LoadContent() {
        String un = dbcon.select("user", "currentuser", "id=1")[0];
        int rows = dbcon.count("select * from tblentry where username='" + un + "'")[0];
        System.out.println(rows);
        String[] _entry = dbcon.selectMaintenance("Entry", "tblentry", "username='" + un + "'");
        String[] _dcreated = dbcon.selectMaintenance("DateCreated", "tblentry", "username='" + un + "'");
        String[] _dupdated = dbcon.selectMaintenance("DateUpdated", "tblentry", "username='" + un + "'");
        String[] _id = dbcon.selectMaintenance("id", "tblentry", "username='" + un + "'");
        try {
            System.out.println(lblUsername.getText() + " " + _entry[0] + " " + _dcreated[0] + " " + _dupdated[0]);

            for (int i = rows - 1; i >= 0; i--) {
                Entry entry = new Entry();

                entry.lblCreated.setText(_dcreated[i]);
                entry.lblUpdated.setText(_dupdated[i]);
                entry.txtEntry.setText(_entry[i]);
                entry.lblID.setText(_id[i]);
                entry.btnDelete.addActionListener((ActionEvent evt) -> {
                    if (JOptionPane.showConfirmDialog(null, "Delete Entry No. " + entry.lblID.getText(), "Delete", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                        dbcon.delete("tblentry", "id=" + entry.lblID.getText());
                        JOptionPane.showMessageDialog(null, "Deleted!");
                        pnlEntry.removeAll();
                        LoadContent();
                        dbcon.setTableSQL("select * from tblentry where username='" + lblUsername.getText() + "'", jTable1);
                    }

                });
                entry.btnUpdate.addActionListener((ActionEvent evt) -> {

                    if (entry.btnUpdate.getText().equals("Edit")) {
                        entry.txtEntry.setEditable(true);
                        entry.btnUpdate.setText("SAVE");
                    } else {
                        dbcon.update("tblentry", new String[]{"Entry", "DateUpdated"},
                                new String[]{entry.txtEntry.getText(), new Date().toString()}, "id=" + entry.lblID.getText());
                        JOptionPane.showMessageDialog(null, "Successfully Updated!");
                        entry.lblUpdated.setText(new Date().toString());
                        entry.txtEntry.setEditable(false);
                        entry.btnUpdate.setText("Edit");
                        dbcon.setTableSQL("select * from tblentry where username='" + lblUsername.getText() + "'", jTable1);
                    }

                });

                pnlEntry.add(entry);
                b = (entry.getPreferredSize().height + 100) * rows;
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public Main() {
        setTitle("My Diary");
        initComponents();
        LoadContent();
        pnlEntry.setPreferredSize(new java.awt.Dimension(500, b));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlEntry = new javax.swing.JPanel();
        pnlOptions = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEntry = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblUsername = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pnlEntry.setBackground(new java.awt.Color(0, 102, 102));
        jScrollPane2.setViewportView(pnlEntry);

        getContentPane().add(jScrollPane2);

        pnlOptions.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("How's your day?");

        txtEntry.setColumns(20);
        txtEntry.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtEntry.setLineWrap(true);
        txtEntry.setRows(5);
        txtEntry.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtEntry);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search Something");

        txtSearch.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        lblUsername.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("USERNAME");

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("LOGOUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOptionsLayout = new javax.swing.GroupLayout(pnlOptions);
        pnlOptions.setLayout(pnlOptionsLayout);
        pnlOptionsLayout.setHorizontalGroup(
            pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtSearch)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOptionsLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUsername)))
                .addContainerGap())
        );
        pnlOptionsLayout.setVerticalGroup(
            pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOptionsLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pnlOptions);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!txtEntry.getText().equals("")) {
            Date date = new Date();
            String d = date.toString();
            System.out.println(d);
            dbcon.insert("tblentry", new String[]{"Username", "Entry", "DateCreated", "DateUpdated"}, new String[]{lblUsername.getText(), txtEntry.getText(), d, d});
            JOptionPane.showMessageDialog(null, "Status Posted!");
            txtEntry.setText("");
            pnlEntry.removeAll();
            LoadContent();
            dbcon.setTableSQL("select * from tblentry where username='" + lblUsername.getText() + "'", jTable1);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            dbcon.setTableSQL("SELECT * FROM tblentry WHERE CONCAT(id, Entry, DateCreated, DateUpdated) like '%" + txtSearch.getText() + "%' and Username='" + lblUsername.getText() + "'", jTable1);
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Logout your account?", "Logout", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            Login login = new Login();
            login.setLocationRelativeTo(null);
            login.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        JOptionPane.showMessageDialog(null, jTable1.getValueAt(row, 2));
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable jTable1;
    public javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlEntry;
    private javax.swing.JPanel pnlOptions;
    private javax.swing.JTextArea txtEntry;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
